title: "Masud Rahman"
description: "Research and analytics portfolio"
url: "https://masud90.github.io"
baseurl: ""

markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# GA4: set your Measurement ID later
google_analytics:
  id: "G-Q7HK9L14NH"   # GA4 Measurement ID (we’ll keep the classic snippet for simplicity)

permalink: /:title/

collections:
  projects:
    output: true
    permalink: /projects/:name/

sass:
  style: compressed

exclude:
  - old_site/
  - scripts/
  - node_modules/
  - .github/
  - README.md