menu:
- {name: 'recent works', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/masud90'}
- {icon: 'twitter', link: 'https://twitter.com/masudtweets'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/masud90'}
- {icone: 'orcid', link: 'https://orcid.org/0000-0001-8991-8253'}

contacts:
- {name: 'Masud Rahman', title: 'Economist', department: 'UNHCR', institution: '', institution_address: '', phone: '', email: '', office: '', twitter: 'https://twitter.com/masudtweets', image: 'assets/img/contact.jpg'}
