menu:
- {name: 'recent works', url: '/publications'}
- {name: 'data science', url: '/datascience'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/masud90'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/masud90'}
- {icon: 'square-x-twitter', link: 'https://x.com/masudtweets'}

contacts:
- {name: 'Masud Rahman', title: 'Economist', department: '', institution: 'UN Refugee Agency (UNHCR)', institution_address: 'Nairobi, Kenya', phone: '', email: '', office: '', twitter: '[@masudtweets](https://x.com/masudtweets)'}
